### ISSUE TITLE
Allow customization of the format

### ISSUE THREAD

**Issue by BrainStone** [olets/zsh-window-title#2]
Hi. I really like this project, however one thing that I'm missing is customization of the format!

I would love to be able to have a format akin to `<user>@<host> - <cwd> - <command>`. Having 1 or 2 variables that dictate the format of the window title would be lovely!

**Comment by olets** [comment]
Hi @BrainStone! Glad to hear you find it useful.

Thanks for the idea. A customizable prefix seems like a reasonable feature. Then you could configure the prefix to be `<user>@<host>`, and someone else could set it to something else.

Would you be interested in contributing the enhancement? I picture a new `ZSH_WINDOW_TITLE_PREFIX`, modeled on zwt's directory depth.

**Comment by BrainStone** [comment]
In principle I'm always looking to contribute, but frankly speaking I'm new to zsh and when I looked at the code it was just a jumble to me.

But honestly speaking I think having two variables that dictate the entire layout would make more sense (one without a command running and one with a command running of course). This allows to customize the prefix, suffix and even how exactly the directory and command are displayed. Something like `ZSH_WINDOW_TITLE_IDLE` and `ZSH_WINDOW_TITLE_ACTIVE`, which naturally both have the currently layouts as defaults if unset.

I will have a go at it myself but can't promise anything of course 😅

**Comment by BrainStone** [comment]
Turns out this was easier than I though. And harder than it initially seemed like.

Anyways that was quite the fun little dive into zsh's docs (spent well over 30 minutes looking for the `(e)` modifier). I hope the MR is alright!

For the curious, this is the format I currently use:

```zsh
export ZSH_WINDOW_TITLE_DIRECTORY_DEPTH=4
export ZSH_WINDOW_TITLE_IDLE='%n@%M - %$ZSH_WINDOW_TITLE_DIRECTORY_DEPTH~'
export ZSH_WINDOW_TITLE_ACTIVE='%n@%M - %$ZSH_WINDOW_TITLE_DIRECTORY_DEPTH~ - %40>...>$1%>>'
```

**Comment by olets** [comment]
If anyone else is interested in completely customizing the format, my recommendation is to ditch this plugin and write your own solution. You too might find it's easier than you think! If you want a spoiler, see my comment in PR #3 for the format

Thanks again @BrainStone!
