### ISSUE TITLE
Support for setting tmux window titles

### ISSUE THREAD

**Issue by smeetrs** [olets/zsh-window-title#4]
When running zsh inside tmux, it would be useful if zsh can set the tmux window titles. To add this feature, I believe it only requires to check the value of TERM variable and depending on its value, the correct set of escape sequences need to be used in the `echo` statement.

For xterm*, `'builtin' 'echo' -ne "\033]0;$title\007"`

For screen*/tmux*, `'builtin' 'echo' -ne "\033k$title\033\\"`

**Comment by olets** [comment]
Thanks for the suggestion!

I don't use tmux but would be happy to consider a pull request (with instructions for how to confirm it works).

**Comment by olets** [comment]
Released in [v1.2.0](https://github.com/olets/zsh-window-title/releases/tag/v1.2.0). Thanks for the contribution and for your patience!
