### ISSUE TITLE
Update title with actual command name when running with sudo

### ISSUE THREAD

**Issue by smeetrs** [olets/zsh-window-title#6]
When running any command with sudo, the title shows 'sudo' as the running process since the plugin code always picks up the first word in the issued command. Instead, in such cases, the title should be updated with the command name that follows sudo.

**Comment by olets** [comment]
This slipped through the cracks!

Nice idea. I've added support for something very similar: if you run with sudo, the window title shows `sudo <second word>`.

That's in the latest release, in the `main` branch, and on Homebrew

Thanks for your patience
